import fs from 'node:fs';
// Offline page to review every published art next to the condition it must depict.
const items = JSON.parse(fs.readFileSync('src/data/items.json', 'utf8'));
const destinations = JSON.parse(fs.readFileSync('src/data/destinations.json', 'utf8'));
const manifest = JSON.parse(fs.readFileSync('src/data/art-manifest.json', 'utf8'));
const esc = s => String(s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const extra = { nery: 'Nery — conferir rosto, roupa e mãos; jaleco sem marca inventada.', bg: 'Cenário — sem pessoas, textos, sacos ou coletores.', badge: 'Medalha — sem texto; emblema legível em tamanho pequeno.' };
const itemCards = [...destinations.map(d => ({ id: d.id, name: d.name, image: manifest[d.id.replace('_', '-')], condition: 'Destino: conferir equipamento e identificação utilizados no HU.' })), ...items];
const known = new Set([...destinations.map(d => d.id.replace('_', '-')), ...items.map(i => i.id)]);
const others = Object.entries(manifest).filter(([key]) => !known.has(key)).map(([key, image]) => ({ id: key, name: key, image, condition: extra[key.split('-')[0]] ?? '' }));
const cards = [...others, ...itemCards];
const sections = cards.map(i => `<article data-search="${esc((i.name + ' ' + i.id).toLowerCase())}"><figure>${i.image ? `<img src="data:image/webp;base64,${fs.readFileSync('public/' + i.image).toString('base64')}" alt="${esc(i.name)}">` : `<span>Arte pendente${i.enabled === false ? ' · caso suspenso' : ''}</span>`}</figure><small>${esc(i.id)}${i.image ? ' · ' + esc(i.image.replace('art/', '')) : ''}</small><h2>${esc(i.name)}</h2><p>${esc(i.condition)}</p></article>`).join('');
const done = items.filter(i => i.enabled && i.image).length, total = items.filter(i => i.enabled).length;
fs.mkdirSync('output', { recursive: true });
fs.writeFileSync('output/Catalogo-de-artes.html', `<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Destino Certo — catálogo de artes</title><style>body{font:16px system-ui;background:#edf4ed;color:#173e30;margin:24px}h1{font-size:2rem}input{font:inherit;padding:14px;border:1px solid #a8c4ad;border-radius:12px;width:min(90%,500px)}main{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:18px;margin-top:24px}article{background:white;padding:18px;border-radius:20px;border:1px solid #dae7dc}figure{margin:0;display:grid;place-items:center;height:230px;background:repeating-conic-gradient(#f1f4f0 0 25%,#e6ece5 0 50%) 0 0/24px 24px;border-radius:12px}img{max-width:100%;height:210px;object-fit:contain}figure span{color:#7a8f82}h2{font-size:1.1rem}p{font-size:.88rem;line-height:1.5}small{display:block;margin-top:16px;color:#597262}[hidden]{display:none!important}</style><h1>Destino Certo · catálogo de artes</h1><p>Itens do jogo com arte própria: <strong>${done}/${total}</strong>. O fundo quadriculado mostra a transparência. Versões ilustrativas em validação institucional.</p><label>Buscar elemento<br><input type="search" placeholder="Ex.: seringa, tecido, nery, badge"></label><main>${sections}</main><script>document.querySelector('input').oninput=e=>{const term=e.target.value.toLowerCase();document.querySelectorAll('article').forEach(c=>c.hidden=!c.dataset.search.includes(term))}</script></html>`);
console.log(`Catálogo offline: output/Catalogo-de-artes.html (${done}/${total} itens com arte)`);
